version: 2.1
jobs:
  hello:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout
      - run: echo "Hello"
  build:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout
      - run: node -v
workflows:
  main:
    jobs:
      - hello